stages:
  - test
  - build

frontend-test:
  image: node:latest
  stage: test
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run test

backend-test:
  image: node:latest
  stage: test
  before_script:
    - cd backend
    - npm install
  script:
    - npm run unittest

frontend-build:
  image: node:latest
  stage: build
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run build

backend-build:
  image: node:latest
  stage: build
  before_script:
    - cd backend
    - npm install
  script:
    - npm run build
