stages:
  - test
  - build
  - deploy

frontend-test:
  image: node:latest
  stage: test
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run test

backend-test:
  image: node:latest
  stage: test
  before_script:
    - cd backend
    - npm install
  script:
    - npm run unittest

frontend-build:
  image: node:latest
  stage: build
  before_script:
    - cd frontend
    - npm install
  script:
    - npm run build

backend-build:
  image: node:latest
  stage: build
  before_script:
    - cd backend
    - npm install
  script:
    - npm run build

frontend-deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - cd frontend
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
